import pandas as pd

def load_data():
    df = pd.DataFrame([
        {
            "day": 1,
            "date": "2026-07-16",
            "from": "Milano",
            "to": "Domodossola",
            "type": "transfer",
            "distance_km": None,
            "elevation_up": None,
            "elevation_down": None,
            "time_h": None,
            "stay": "Apartment - Domodossola",
            "cost": 150,
            "currency":"EUR",
            "link": "https://secure.booking.com/confirmation.el.html?label=gen173nr-10CAEoggI46AdIM1gEaFyIAQGYATO4ARfIAQzYAQPoAQH4AQGIAgGoAgG4Asvv780GwAIB0gIkNWU3YzY5ZTEtMDhhOS00YTI5LWJkOTgtYjgyMWI5NGE0YTY32AIB4AIB&sid=8df3b9f6feab32d1b4c2fb0b72d0d9d8&aid=304142&auth_key=67YzRA5nnWrTky7n&source=mytrips",
            "notes": "Reach Domodossola via train. Bus routes for next day transfer are  [here](https://www.comazzibus.com/wp/wp-content/uploads/2026/03/DOMODOSSOLA-MACUGNAGA-INVERNALE_def.pdf)."
        },
        {
            "day": 2,
            "date": "2026-07-17",
            "from": "Macugnaga",
            "to": "Monte Moro",
            "type": "hiking",
            "distance_km": 7.6,
            "elevation_up": 1490,
            "elevation_down": 10,
            "time_h": 4,
            "stay": "Rifugio Oberto Maroli (2780m)",
            "cost": 80,
            "currency":"CHF",
            "link": "https://www.montemoropass.it",
            "notes": "Cable car may not work. Possible snow at 2900m."
        },
        {
            "day": 3,
            "date": "2026-07-18",
            "from": "Monte Moro",
            "to": "Saas-Fee",
            "type": "hiking",
            "distance_km": 17.2,
            "elevation_up": 300,
            "elevation_down": 1295,
            "time_h": 5.3,
            "stay": "Apartment - Saas Fee",
            "cost": 408,
            "currency":"CHF",
            "link": "https://secure.booking.com/confirmation.el.html?label=gen173nr-10CAEoggI46AdIM1gEaFyIAQGYATO4ARfIAQzYAQPoAQH4AQGIAgGoAgG4Asvv780GwAIB0gIkNWU3YzY5ZTEtMDhhOS00YTI5LWJkOTgtYjgyMWI5NGE0YTY32AIB4AIB&sid=8df3b9f6feab32d1b4c2fb0b72d0d9d8&aid=304142&auth_key=3MU7mWahOzErz6dh&source=mytrips",
            "notes": ""
        },
        {
            "day": 4,
            "date": "2026-07-19",
            "from": "Saas-Fee",
            "to": "Grachen",
            "type": "hiking",
            "distance_km": 20.3,
            "elevation_up": 995,
            "elevation_down": 1180,
            "time_h": 7.2,
            "stay": "Grachen",
            "cost": 445,
            "currency":"CHF",
            "link": "https://secure.booking.com/confirmation.el.html?label=gen173nr-10CAEoggI46AdIM1gEaFyIAQGYATO4ARfIAQzYAQPoAQH4AQGIAgGoAgG4AvLAqM4GwAIB0gIkYjcwYjE3YzYtM2I3Ni00OTRmLTliMGUtZjNkYWVmZGExY2M32AIB4AIB&sid=8df3b9f6feab32d1b4c2fb0b72d0d9d8&aid=304142&auth_key=WXzB0XmRBSE66pUj&source=mytrips",
            "notes": ""
        },
        {
            "day": 5,
            "date": "2026-07-20",
            "from": "Grachen",
            "to": "Europahutte",
            "type": "hiking",
            "distance_km": 17.0,
            "elevation_up": 1455,
            "elevation_down": 805,
            "time_h": 6.6,
            "stay": "Europahutte",
            "cost": 95,
            "currency":"CHF",
            "link": "https://www.randa.ch/en/tourism/mountain-huts/europa-hut/",
            "notes": "Check trail conditions (Europaweg closures)."
        },
        {
            "day": 6,
            "date": "2026-07-21",
            "from": "Europahutte",
            "to": "Randa",
            "type": "hiking",
            "distance_km": 4.0,
            "elevation_up": 0,
            "elevation_down": 800,
            "time_h": 6.4,
            "stay": "Apartment - Randa",
            "cost": 389.47,
            "currency":"EUR",
            "link": "https://www.airbnb.com/l/HboTDHw1?s=67&unique_share_id=2f3f5ee4-8917-4285-b4ef-23e3d0be60aa",
            "notes": ""
        },
        {
            "day": 7,
            "date": "2026-07-22",
            "from": "Randa",
            "to": "Gandegghutte",
            "type": "hiking",
            "distance_km": 10.5,
            "elevation_up": 1450,
            "elevation_down": 35,
            "time_h": 4.2,
            "stay": "Gandegghutte",
            "cost": 103,
            "currency":"CHF",
            "link": "https://www.gandegg.ch/mountain-hut.html",
            "notes": ""
        },
        {
            "day": 8,
            "date": "2026-07-23",
            "from": "Zermatt",
            "to": "Brig",
            "type": "transfer",
            "distance_km": None,
            "elevation_up": None,
            "elevation_down": None,
            "time_h": None,
            "stay": "Hotel - Brig",
            "cost": 386,
            "currency":"CHF",
            "link": "https://secure.booking.com/confirmation.el.html?label=gen173nr-10CAEoggI46AdIM1gEaFyIAQGYATO4ARfIAQzYAQPoAQH4AQGIAgGoAgG4Asvv780GwAIB0gIkNWU3YzY5ZTEtMDhhOS00YTI5LWJkOTgtYjgyMWI5NGE0YTY32AIB4AIB&sid=8df3b9f6feab32d1b4c2fb0b72d0d9d8&aid=304142&auth_key=sCWtTpcmfowGwl81&source=mytrips",
            "notes": ""
        },
        {
            "day": 9,
            "date": "2026-07-24",
            "from": "Brig",
            "to": "Milano",
            "type": "transfer",
            "distance_km": None,
            "elevation_up": None,
            "elevation_down": None,
            "time_h": None,
            "stay": "-",
            "cost": 0,
            "link": None,
            "notes": "Return"
        }
    ])

    return df